config/routes.rb
Wavepool::Application.routes.draw do
  root to: 'playlists#index'

  get '/login', to: "sessions#new"

  match '/auth/rdio/callback', to: 'sessions#create', via: [:get, :post]
  match '/logout', to: 'sessions#destroy', via: [:get, :post]

  match '/helper', to: redirect('/helper.html'), via: [:get, :post]

  get '/playlists/:rdio_key' => 'playlists#show'
  get '/playlists' => 'playlists#index'
  post '/playlists/:rdio_key' => 'playlists#create', as: "create_playlist"
  match '/playlists/:rdio_key/add_song' => 'playlists#add_song', as: "add_song_to_playlist", via: [:get, :post]
  match '/playlists/:rdio_key/generate_access_code' => 'playlists#generate_access_code', as: "generate_access_code", via: [:get, :post]
  match '/playlists/:rdio_key/expire_access_code' => 'playlists#expire_access_code', as: "expire_access_code", via: [:get, :post]

  post '/connect' => 'connect#connect'

  match '/song_search' => 'song_search#search', as: "song_search", via: [:get, :post]

end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  belongs_to :user

  def self.from_rdio(response, user_id)
    response.each do |playlist|
      next if self.find_by rdio_key: playlist["key"]
      self.create(name: playlist["name"], rdio_key: playlist["key"], user_id: user_id)
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :playlists

  def self.find_or_create_by_sms(sms_receiver)
    user = self.where(phone_number: sms_receiver.from).first_or_initialize
    user.playlist_id = Playlist.find_by(access_code: sms_receiver.body).id
    user.save if user.changed?
    user
  end

  def playlist
    Playlist.find_by id: playlist_id
  end

  def clear_tokens!
    access_token        = nil
    access_token_secret = nil
    self.save!
  end
end

app/controllers/application_controller.rb
require 'rdio_songs'
require 'redis_stack'
require 'sms_song_parser'
require 'twilio_sms_receiver'

class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def sms_song_parser
    @sms_song_parser ||= SmsSongParser.new(sms_receiver.body)
  end

  def sms_receiver
    @sms_receiver ||= TwilioSmsReceiver.from_params(params.clone)
  end

  def redis_stack
    @redis_stack ||= RedisStack.new(sms_receiver.cache_key)
  end

  def rdio_songs
    @rdio_songs ||= RdioSongs.new(playlist_owner) if playlist_owner
  end

  def authenticate
    redirect_to login_path unless current_user
  end

  def current_user
    @current_user ||= User.find_by id: session[:user_id] if session[:user_id]
  end
  helper_method :current_user

  def requester
    @requester ||= User.find_or_create_by_sms(sms_receiver)
  end

  def playlist_owner
    @playlist_owner ||= sms_receiver.playlist.user
  end
end

app/controllers/connect_controller.rb
class ConnectController < ApplicationController
  skip_before_filter :verify_authenticity_token

  def connect
    if sms_receiver.legit_access_code_present? && requester.present?
      twiml_response = Twilio::TwiML::Response.new do |r|
        r.Sms "Thanks! What song would you like to request?"
      end
      render xml: twiml_response.text
    elsif sms_receiver.song_decision?
      params.merge!(rdio_key: sms_receiver.playlist.rdio_key)
      redirect_to add_song_to_playlist_path(params)
    else
      params.merge!(rdio_key: sms_receiver.playlist.rdio_key)
      redirect_to song_search_path(params)
    end
  end
end

app/controllers/echonest_controller.rb
class EchonestController < ApplicationController
  skip_before_filter :verify_authenticity_token

  def search
    redis_stack.push echonest.response
    message = (echonest.songs.present? ? base_response << echonest.to_sms_choices : no_result_response)
    twiml_response = Twilio::TwiML::Response.new do |r|
      r.Sms message
    end
    render xml: twiml_response.text
  end

  private

  def base_response
    "Choose which song you would like to add to the queue:"
  end

  def no_result_response
    "Sorry, we can’t find that one! Check your spelling and try again!"
  end
end

app/controllers/playlists_controller.rb
require 'rdio'

class PlaylistsController < ApplicationController
  before_filter :authenticate, only: [:index, :show, :generate_access_code]
  skip_before_filter :verify_authenticity_token, only: [:add_song]

  def index
    rdio = Rdio.new([ENV["RDIO_CONSUMER_KEY"], ENV["RDIO_CONSUMER_SECRET"]],
                    [current_user.access_token, current_user.access_token_secret])
    @playlists = rdio.call('getPlaylists')["result"]["owned"]
    Playlist.from_rdio(@playlists, current_user.id)
  end

  def show
    @playlist = Playlist.find_by rdio_key: params[:rdio_key]
  end

  def add_song
    result = RdioSongs::ResponseParser.new redis_stack.last
    if result.songs.present?
      rdio_id        = result.songs[sms_receiver.body.to_i - 1].key
      playlist_owner = sms_receiver.playlist.user
      rdio = Rdio.new([ENV["RDIO_CONSUMER_KEY"], ENV["RDIO_CONSUMER_SECRET"]],
                      [playlist_owner.access_token, playlist_owner.access_token_secret])
      rdio.call("addToPlaylist", playlist: sms_receiver.playlist.rdio_key, tracks: rdio_id)
      redis_stack.pop
      head :ok
    else
      twiml_response = Twilio::TwiML::Response.new do |r|
        r.Sms "Sorry! We couldn't process your request :("
      end
      render xml: twiml_response.text
    end
  end

  def create
    playlist_name =  params[:playlistName]
    rdio = Rdio.new([ENV["RDIO_CONSUMER_KEY"], ENV["RDIO_CONSUMER_SECRET"]],
                    [current_user.access_token, current_user.access_token_secret])
    playlist = rdio.call("createPlaylist", name: playlist_name, description: "", tracks: "")["result"]
    Playlist.create(name: playlist["name"], rdio_key: playlist["key"], user_id: current_user.id)

    redirect_to "/playlists/#{playlist["key"]}"
  end

  def generate_access_code
    playlist = Playlist.find_by rdio_key: params[:rdio_key]
    playlist.access_code = generate_code
    if playlist.save
      redirect_to :back, notice: "Successfully created access code"
    else
      redirect_to :back, notice: "FAIL"
    end
  end

  def expire_access_code
    playlist = Playlist.find_by rdio_key: params[:rdio_key]
    playlist.access_code = nil
    if playlist.save
      redirect_to :back, notice: "Successfully expired access code"
    else
      redirect_to :back, notice: "FAIL"
    end
  end

  private

  def generate_code
    SecureRandom.hex(2)
  end
end

app/controllers/sessions_controller.rb
require 'rdio'

class SessionsController < ApplicationController
  before_filter :authenticate, only: [:destroy]

  def new
    rdio = Rdio.new([ENV["RDIO_CONSUMER_KEY"], ENV["RDIO_CONSUMER_SECRET"]])
    @url = rdio.begin_authentication("#{root_url}auth/rdio/callback")
    session[:request_token] = rdio.token[0]
    session[:request_token_secret] = rdio.token[1]
  end

  def create
    rdio = Rdio.new([ENV["RDIO_CONSUMER_KEY"], ENV["RDIO_CONSUMER_SECRET"]],
                    [session[:request_token], session[:request_token_secret]])
    rdio.complete_authentication(params[:oauth_verifier])

    session.delete(:request_token)
    session.delete(:request_token_secret)

    user = User.where(rdio_key: rdio.call('currentUser')['result']['key']).first_or_initialize
    user.access_token        = rdio.token[0]
    user.access_token_secret = rdio.token[1]

    if user.save
      session[:user_id] = user.id
      redirect_to playlists_path
    else
      render :new, notice: "Something went wrong :("
    end
  end

  def destroy
    current_user.clear_tokens!
    session[:user_id] = nil
    redirect_to :root
  end
end

app/controllers/song_search_controller.rb
class SongSearchController < ApplicationController
  skip_before_filter :verify_authenticity_token

  def search
    results = rdio_songs.search(sms_song_parser.artist, sms_song_parser.title)
    redis_stack.push results.response
    message = (results.songs.present? ? results.to_sms_choices : no_result_response)
    twiml_response = Twilio::TwiML::Response.new do |r|
      r.Sms message
    end
    render xml: twiml_response.text
  end

  private

  def no_result_response
    "Sorry! We couldn't process your request! :("
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Wavepool
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag 'http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js'
    = csrf_meta_tags
    %meta{name: "viewport", content: "width=device-width, initial-scale=1, maximum-scale=1"}
    %link{:href => "/wpAppIcon.jpg", :rel => "apple-touch-icon"}

  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container-fluid
          .brand= image_tag "wpLogo.jpg"
          = link_to "Wavepool", root_path, class: "brand brand-title"
          .pull-right
            %ul.nav
              - if current_user
                %li.divider-vertical
                %li= link_to "Logout", logout_path

    .container-fluid
      .row-fluid
        .span-12
          .main
            = yield

app/views/playlists/index.html.haml
%h2.center My Playlists

%ul.nav.nav-tabs.nav-stacked.playlist-list
  - @playlists.each do |playlist|
    %li= link_to playlist["name"], "/playlists/#{playlist["key"]}"

%h2.center Create Playlist
#createPlaylistForm.center
  = form_tag create_playlist_path(rdio_key: "key"), :method => :post do
    #searchField= text_field_tag "playlistName", nil, placeholder: "Playlist name..."
    %input.btn.btn-success.btn-block.center{ :name => "commit", :type => "submit", :value => "create"}

app/views/playlists/show.html.haml
= javascript_include_tag "//www.rdio.com/api/api.js?helper=../helper&client_id=ORZsksGzKwWnxGPE6-r26g"
%script(src="../rdioscripts.js")

%h1.playlist-name= @playlist.name
#playlistKey= @playlist.rdio_key
#userKey= current_user.rdio_key

%p.instructions
  Have your friends text the access code to
  %b 978-278-3217
  to begin adding songs.

.center
  .access_code
    - if @playlist.access_code
      .pull-left
        .action
          = link_to generate_access_code_path do
            %i.icon-refresh
      .message
        = @playlist.access_code
      .pull-right
        .action
          = link_to expire_access_code_path do
            %i.icon-trash
    - else
      .generate-access.message
        = link_to "Click to generate access code", generate_access_code_path

#startPrompt
  #start.center.btn.btn-success.btn-block Start Playlist

#rdioPlayer
  #playbackControls.center
    #previous.btn.btn-primary= image_tag "previous.png"
    #play.btn.btn-primary= image_tag "play.png"
    #pause.btn.btn-primary= image_tag "pause.png"
    #next.btn.btn-primary= image_tag "next.png"

  #songInfo.center
    %img#art
    .clear
    %b Track:
    #track
    %b Artist:
    #artist

  #positionContainer
    #position
      &nbsp;